service: appointment-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - serverless-offline

functions:
  healthCheck:
    handler: src/handlers/healthHandler.healthCheck
    events:
      - http:
          path: health
          method: get

  appointment:
    handler: src/handlers/appointmentHandler.createAppointment
    events:
      - http:
          path: appointments
          method: post

  getAppointments:
    handler: src/handlers/getAppointmentsHandler.getAppointments
    events:
      - http:
          path: appointments/{insuredId}
          method: get
